config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :projects
  resources :materials
  resources :material_lists
  resources :material_needs
  resources :assignments

  root 'static_pages#home'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base

  belongs_to :project
  belongs_to :user
  
end

app/models/material.rb
class Material < ActiveRecord::Base
end

app/models/material_list.rb
class MaterialList < ActiveRecord::Base
  
  belongs_to :project
  has_many :material_needs, dependent: :destroy
  
end

app/models/material_need.rb
class MaterialNeed < ActiveRecord::Base
  
  belongs_to :material_list
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  has_one :material_list, dependent: :destroy
  has_many :assignments, dependent: :destroy
  has_many :users, through: :assignments

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :assignments
  has_many :projects, through: :assignments
  
  validates :name, :email, presence: true
  validates :email, uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  # todo - I feel like I shouldn't have to have hard reference so many other classes in this controller

  def index
    # todo - asking for users instead of assignments seems like a red flag.
    @users = User.all
  end

  def new
    @assignment = Assignment.new

    # All assignments belong to a project and they will have to attach to it eventually
    @project = Project.find(params[:project_id])

    # Loading up all users so that the view has access to them
    @users = User.all
  end

  def create
    assigned_project = Project.find(params[:project_id])
    assigned_user = User.find(params[:assignment][:user])
    @assignment = Assignment.create(project: assigned_project, user: assigned_user)
    
    redirect_to projects_path
  end
  
  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy

    redirect_to projects_path
  end

end

app/controllers/material_lists_controller.rb
class MaterialListsController < ApplicationController

  def new
    @material_list = MaterialList.new
    
    # No view to render and redirection does not work with a POST, so just go right into the creation method
    create
  end
  
  def create
    parent_project = Project.find(params[:project_id])
    MaterialList.create(project: parent_project)
    
    redirect_to projects_path
  end

end

app/controllers/material_needs_controller.rb
class MaterialNeedsController < ApplicationController

  def new
    @material_need = MaterialNeed.new
    
    # All needs derive from some project and they will have to attach to it eventually
    @project_id = params[:project_id]
  end

  def create
    parent_list = Project.find(params[:project_id]).material_list
    @material_need = MaterialNeed.create(material_need_params.merge(material_list: parent_list))
    
    redirect_to projects_path
  end

  def edit
    @material_need = MaterialNeed.find(params[:id])
  end

  def update
    @material_need = MaterialNeed.find(params[:id])

    @material_need.update(material_need_params)

    redirect_to projects_path
  end
  
  def destroy
    @material_need = MaterialNeed.find(params[:id])
    @material_need.destroy

    redirect_to projects_path
  end


  private


  def material_need_params
    params.require(:material_need).permit(:name, :quantity)
  end
  
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController

  def index
    @materials = Material.all
  end

  def new
    @material = Material.new
  end

  def create
    Material.create(material_params)

    redirect_to action: 'index'
  end

  def edit
    @material = Material.find(params[:id])
  end

  def update
    @material = Material.find(params[:id])

    @material.update(material_params)

    redirect_to action: 'index'
  end

  def destroy
    @material = Material.find(params[:id])
    @material.destroy

    redirect_to action: 'index'
  end


  private


  def material_params
    params.require(:material).permit(:name, :quantity, :unit)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.paginate(page: params[:page])
  end

  def new
    @project = Project.new
  end

  def create
    Project.create(project_params)

    redirect_to action: 'index'
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    @project.update(project_params)

    redirect_to action: 'index'
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to action: 'index'
  end


  private


  def project_params
    params.require(:project).permit(:name, :description)
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.now[:notice] = "#{@user.name.capitalize} has been created!"
    else
      flash.now[:warning] = "No user has been created!"
    end
    render 'new'
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    render 'show'
  end

  def destroy
    user = User.find(params[:id])

    # todo - this doesn't seem to work
    flash.now[:notice] = "#{user.name} was removed."

    user.destroy


    redirect_to users_path
  end

  def new
    @user = User.new
  end

  private
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/material_lists_helper.rb
module MaterialListsHelper
end

app/helpers/material_needs_helper.rb
module MaterialNeedsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/assignments/_create_assignment_fields.html.erb
<%= form.label :user %>
<%= form.select :user do %>

    <% users.each do |user| %>
        <%= content_tag(:option, user.name, value: user.id) %>
    <% end %>

<% end %>

app/views/assignments/index.html.erb
<h1>All Project Assignments</h1>

<% @users.each do |user| %>

    <% if user.assignments && !user.assignments.empty? %>

        <h3 id="<%= user.id %>"><%= user.name %></h3>

        <ul>
          <% user.projects.each do |project| %>
              <li><%= project.name %></li>
          <% end %>
        </ul>

    <% end %>

<% end %>

app/views/assignments/new.html.erb
<div class="text-center">
  <h1>Assign employee to <%= @project.name %></h1>
</div>

<div>
  <%= form_for(@assignment) do |form| %>
      <% # todo - this doesn't seem like the proper way to do this  %>
      <%= render 'create_assignment_fields', form: form, users: @users %>
      <%= hidden_field_tag 'project_id', @project.id %>
      <%= form.submit "Add employee", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/material_needs/_create_material_need_fields.html.erb
<%= form.label :name %>
<%= form.text_field :name %>

<%= form.label :quantity %>
<%= form.text_field :quantity %>

app/views/material_needs/edit.html.erb
<div class="text-center">
  <h1>Edit needed material</h1>
</div>

<div>
  <%= form_for(@material_need) do |form| %>
    <%= render 'create_material_need_fields', form: form %>
    <%= form.submit "Update needed material", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/material_needs/new.html.erb
<div class="text-center">
  <h1>Add new material</h1>
</div>
<div>
  <%= form_for(@material_need) do |form| %>
    <%= render 'create_material_need_fields', form: form %>
    <%= hidden_field_tag 'project_id', @project_id %>  
    <%= form.submit "Add material", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/materials/_create_material_fields.html.erb
<%= form.label :name %>
<%= form.text_field :name %>

<%= form.label :quantity %>
<%= form.text_field :quantity %>

<%= form.label :unit %>
<%= form.text_field :unit %>

app/views/materials/edit.html.erb
<div class="text-center">
  <h1>Edit material</h1>
</div>

<div>
  <%= form_for(@material) do |form| %>
    <%= render 'create_material_fields', form: form %>
    <%= form.submit "Update material", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/materials/index.html.erb
<h1>Material Inventory</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Quantity</th>
    <th>Unit</th>
  </tr>

  <% @materials.each do |material| %>
    <tr>
      <td><%= material.name %></td>
      <td><%= material.quantity %></td>
      <td><%= material.unit %></td>
      <td><%= link_to 'Edit', edit_material_path(id: material.id) %></td>
      <td><%= link_to 'Delete', material_path(id: material.id), method: :delete %></td>
    </tr>
  <% end %>
  
</table>

<%= link_to 'Add material', new_material_path %>

app/views/materials/new.html.erb
<div class="text-center">
  <h1>Add new material</h1>
</div>
<div>
  <%= form_for(@material) do |form| %>
    <%= render 'create_material_fields', form: form %>
    <%= form.submit "Add material", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/projects/_create_project_fields.html.erb
<%= form.label :name %>
<%= form.text_field :name %>

<%= form.label :description %>
<%= form.text_field :description %>

app/views/projects/_project.html.erb
<li>
  <div><%= project.name %></div>
  <div><%= project.description %></div>
  <div><%= link_to 'Edit Project', edit_project_path(id: project.id) %></div>
  <div><%= link_to 'Delete Project', project_path(id: project.id), method: :delete %></div>

  <% #todo - extract these display possibilities into their own partials   %>
  <% if project.material_list %>

      <div>Materials needed</div>

      <table>
        <tr>
          <th>Type</th>
          <th>Quantity</th>
        </tr>


        <% project.material_list.material_needs.each do |need| %>
            <tr>
              <td><%= need.name %></td>
              <% #todo - add material units to these amounts   %>
              <td><%= need.quantity %></td>
              <td><%= link_to 'Edit', edit_material_need_path(id: need.id) %></td>
              <td><%= link_to 'Remove', material_need_path(id: need.id), method: :delete %></td>
            </tr>
      <% end %>

      </table>

      <%= link_to 'Add needed material', new_material_need_path(project_id: project.id) %>

  <% else %>

      <%= link_to 'Add Materials To Project', new_material_list_path(project_id: project.id) %>

  <% end %>

  <% unless project.assignments.empty? %>

      <div>Assigned employees</div>

      <table>
        <tr>
          <th>Name</th>
        </tr>


        <% project.users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= link_to 'Remove', assignment_path(id: Assignment.find_by(project_id: project.id, user_id: user.id).id), method: :delete %></td>
            </tr>
        <% end %>

      </table>

  <% end %>

  <div><%= link_to 'Assign Employees To Project', new_assignment_path(project_id: project.id) %></div>

</li>

app/views/projects/edit.html.erb
<div class="text-center">
  <h1>Edit project</h1>
</div>

<div>
  <%= form_for(@project) do |form| %>
    <%= render 'create_project_fields', form: form %>
    <%= form.submit "Update project", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/projects/index.html.erb
<h1>All Projects</h1>
<%= will_paginate %>

<ul class="employees">
  <%= render @projects %>
</ul>

<%= will_paginate %>

<%= link_to 'Add project', new_project_path %>

app/views/projects/new.html.erb
<div class="text-center">
  <h1>Add new project</h1>
</div>
<div>
  <%= form_for(@project) do |form| %>
    <%= render 'create_project_fields', form: form %>
    <%= form.submit "Add project", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/static_pages/home.html.erb
<div class="center hero-unit text-center">
  <h1>Superior Construction Internal Application (SCIA)</h1>

  <h2>
    Requirements List
  </h2>
  <ol>
    <li>
      Jill just got married and needs to change her name.  The current app does not allow this action to happen.
      Allow updates to the employees.
    </li>
    <li>
      We've noticed duplicate users on the Users index page. Write a rake task to clean these entries up and put in
      a fix to not allow this to happen.
    </li>
    <li>
      We currently have a excel list of all employees working on each project.  We would like to see this data in
      the app.  Each project should list the employees working on the project and each employee should show which projects
      they are working on.
    </li>
    <li>
      Each project has a list of materials.  Define the model and relationships.  Each project should show the materials needed
      to complete the project.  We would also like to have an inventory page to keep track of all our materials.
    </li>
  </ol>
</div>

app/views/users/_create_fields.html.erb
<%#= render 'shared/error_messages', object: f.object %>

<%= form.label :name %>
<%= form.text_field :name %>

<%= form.label :email %>
<%= form.text_field :email %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  |
  <%= link_to user.email, user %>
  |
  <%= link_to 'See assignments', assignments_path(anchor: user.id) %>
</li>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>Edit <%= @user.name %></h1>
</div>

<div>
  <%= form_for(@user) do |form| %>
      <%= render 'create_fields', form: form %>
      <%= form.submit "Update employee", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>All Employees</h1>
<%= will_paginate %>

<ul class="employees">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Create new Users</h1>
</div>
<div>
  <%= form_for(@user) do |form| %>
      <%= render 'create_fields', form: form %>
      <%= form.submit "Create a new User", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="center hero-unit">
  <%= @user.name %>

  <%= link_to 'Edit', edit_user_path(id: @user.id) %>
  <%= link_to 'Remove', user_path(id: @user.id), method: :delete %>

</div>