config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :projects
  resources :materials
  resources :material_lists
  resources :material_needs
  resources :assignments

  root 'static_pages#home'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base

  belongs_to :project
  belongs_to :user
  
end

app/models/material.rb
class Material < ActiveRecord::Base
end

app/models/material_list.rb
class MaterialList < ActiveRecord::Base
  
  belongs_to :project
  has_many :material_needs, dependent: :destroy
  
end

app/models/material_need.rb
class MaterialNeed < ActiveRecord::Base
  
  belongs_to :material_list
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  has_one :material_list, dependent: :destroy
  has_many :assignments, dependent: :destroy
  has_many :users, through: :assignments

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :assignments
  has_many :projects, through: :assignments
  
  validates :name, :email, presence: true
  validates :email, uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  # todo - I feel like I shouldn't have to have hard reference so many other classes in this controller

  def index
    # todo - asking for users instead of assignments seems like a red flag.
    @users = User.all
  end

  def new
    @assignment = Assignment.new

    # All assignments belong to a project and they will have to attach to it eventually
    @project = Project.find(params[:project_id])

    # Loading up all users so that the view has access to them
    @users = User.all
  end

  def create
    assigned_project = Project.find(params[:project_id])
    assigned_user = User.find(params[:assignment][:user])
    @assignment = Assignment.create(project: assigned_project, user: assigned_user)
    
    redirect_to projects_path
  end
  
  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy

    redirect_to projects_path
  end

end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController

  def index
    @materials = Material.all
  end

  def new
    @material = Material.new
  end

  def create
    Material.create(material_params)

    redirect_to action: 'index'
  end

  def edit
    @material = Material.find(params[:id])
  end

  def update
    @material = Material.find(params[:id])

    @material.update(material_params)

    redirect_to action: 'index'
  end

  def destroy
    @material = Material.find(params[:id])
    @material.destroy

    redirect_to action: 'index'
  end


  private


  def material_params
    params.require(:material).permit(:name, :quantity, :unit)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.paginate(page: params[:page])
  end

  def new
    @project = Project.new
  end

  def create
    Project.create(project_params)

    redirect_to action: 'index'
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    @project.update(project_params)

    redirect_to action: 'index'
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to action: 'index'
  end


  private


  def project_params
    params.require(:project).permit(:name, :description)
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.now[:notice] = "#{@user.name.capitalize} has been created!"
    else
      flash.now[:warning] = "No user has been created!"
    end
    render 'new'
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    render 'show'
  end

  def destroy
    user = User.find(params[:id])

    # todo - this doesn't seem to work
    flash.now[:notice] = "#{user.name} was removed."

    user.destroy


    redirect_to users_path
  end

  def new
    @user = User.new
  end

  private
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/material_lists_helper.rb
module MaterialListsHelper
end

app/helpers/material_needs_helper.rb
module MaterialNeedsHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
      <div class="container-fluid">
        <p class="pull-left">
          Interview Project &copy; Chris Barthol 2015
        </p>
        <span class="pull-right">
            About Contact
        </span>
      </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Superior Construction</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">About</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Projects', projects_path %></li>
            <li><%= link_to 'Materials', materials_path %></li>
            <!-- <li><a href="#">Schedule</a></li> -->
            <li role="separator" class="divider"></li>
            <li><a href="#">Consultation</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Employees <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'All', users_path %></li>
            <li><%= link_to 'New', new_user_path %></li>
          </ul>
        </li>        
        <!-- <li><a href="#">User</a></li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyRailsInterviewApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>